title: WINGs 2026
page-top-title: WINGs 2026
top-section-bg-text: WINGs 2026 is the sixth instalment of an annual retreat for women and other underrepresented genders in number theory and geometry.
home-subtitle: Dates: 13-16th April, Location: Cheltenham, UK
copyright-text: ...
